s="harish chowdary k"
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.title())
print(s.capitalize())
print(s.isupper())
print(s.islower())
print(s.isalnum())
print(s.isalpha())
print(s.isspace())
print(s.istitle())
print(s.rindex('c'))
print(s.find('h'))
print(s.rfind('h'))
print(s.count('h'))
print(s.startswith('k ',6))
print(s.startswith('h'))
print(s.endswith('k'))
print(s.split())
print(s.split('w'))
print(s.partition('w'))

