'''import turtle
s=turtle.Turtle()
turtle.bgcolor("light blue")
s.fillcolor("green")
s.begin_fill()
s.circle(50)
s.end_fill()
s.penup()
s.pendown()
s.forward(20)
s.goto(0,50)
for i in range(10):
    s.right(36)
    s.forward(100)
    turtle.mainloop()'''
import turtle
s=turtle.Turtle()
turtle.bgcolor("yellow")
s.fillcolor("red")
s.begin_fill()
s.circle(50)
s.end_fill()
s.penup()
s.pendown()
for i in range(10):
    s.forward(100)
    s.goto(0,50)
    s.right(36)
s.penup()
s.goto(0,0)
s.pendown()
s.begin_fill()
s.circle(50)
s.end_fill()
turtle.mainloop()
